# Generated by Django 4.2.12 on 2024-07-19 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=60)),
                ("address", models.CharField(max_length=60)),
                ("phone", models.CharField(max_length=10)),
                ("about", models.TextField()),
                (
                    "possition",
                    models.CharField(
                        choices=[("Manager", "manager"), ("SDE", "sde"), ("Pr", "pr")],
                        max_length=50,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.company"
                    ),
                ),
            ],
        ),
    ]
